spring:
  application:
    name: consul-service
server:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        health-check-path: ${managerment.context-path/health}
#        health-check-interval: 15s
        instance-id: ${spring.application.name}:${server.port}
        tags: test=zbw,zzz
  port: 9988
